# Generated by Django 2.2.9 on 2020-08-21 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("posts", "0005_auto_20200819_0940"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="edit_date",
            field=models.DateTimeField(
                auto_now=True,
                help_text="Дата последнего редактирования",
                verbose_name="Дата последнего редактирования",
            ),
        ),
    ]
